# Generated by Django 5.1.1 on 2024-09-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDb',
            fields=[
                ('StudId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=50)),
                ('Course', models.CharField(max_length=50)),
            ],
        ),
    ]
