# Generated by Django 3.2.10 on 2024-09-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDb',
            fields=[
                ('TeacherId', models.AutoField(primary_key=True, serialize=False)),
                ('tName', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Mobile', models.IntegerField()),
            ],
        ),
    ]
