# Generated by Django 5.1.1 on 2024-09-19 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empdb',
            old_name='Course',
            new_name='Position',
        ),
    ]
